# Generated by Django 3.2.17 on 2023-02-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table=None,
        ),
    ]
