# Generated by Django 4.1.3 on 2023-01-24 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.JSONField()),
                ('deploy_status', models.IntegerField(choices=[(1, 'Prepared'), (2, 'Deployed'), (0, 'Failed')], null=True)),
                ('running_status', models.IntegerField(choices=[(1, 'Started'), (2, 'Running'), (3, 'Stopped'), (0, 'Failed')], null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
