# Generated by Django 4.1.3 on 2023-01-24 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(default='us-west-1')),
                ('security_group', models.TextField(null=True)),
                ('subnet', models.TextField(null=True)),
                ('date_created_or_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aws_components', to='plan.plan')),
            ],
        ),
        migrations.CreateModel(
            name='EC2',
            fields=[
                ('awscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aws.awscomponent')),
                ('aws_component', models.TextField(default='ec2')),
                ('ec2_instance_id', models.TextField(null=True)),
                ('ec2_status', models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed')], default=1)),
                ('instance_type', models.TextField(default='t2.micro')),
                ('image_id', models.TextField(default='ami-0f5e8a042c8bfcd5e')),
            ],
            bases=('aws.awscomponent',),
        ),
        migrations.CreateModel(
            name='LB',
            fields=[
                ('awscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aws.awscomponent')),
                ('aws_component', models.TextField(default='lb')),
                ('lb_instance_id', models.TextField(null=True)),
                ('lb_status', models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed')], default=1)),
                ('lb_type', models.TextField(default='ALB')),
            ],
            bases=('aws.awscomponent',),
        ),
        migrations.CreateModel(
            name='AwsCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key', models.TextField()),
                ('aws_access_secret', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
