# Generated by Django 4.1.3 on 2023-01-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscreds',
            name='aws_iam_user',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='awscreds',
            name='aws_private_key_pair_pem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ec2',
            name='instance_key_pair',
            field=models.TextField(default='cloudskin_key'),
        ),
        migrations.AlterField(
            model_name='awscomponent',
            name='security_group',
            field=models.TextField(default='sg-0f2b88c10abf752e3', null=True),
        ),
        migrations.AlterField(
            model_name='awscomponent',
            name='subnet',
            field=models.TextField(default='subnet-0a6da46fb837b5a32', null=True),
        ),
        migrations.AlterField(
            model_name='awscreds',
            name='aws_access_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='awscreds',
            name='aws_access_secret',
            field=models.TextField(null=True),
        ),
    ]
