# Generated by Django 4.1.3 on 2023-01-31 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_awscreds_aws_iam_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscreds',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awscreds',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
