# Generated by Django 4.1.3 on 2023-01-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_awscreds_date_created_awscreds_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscreds',
            name='aws_private_key_pair_pem_name',
            field=models.TextField(null=True),
        ),
    ]
