# Generated by Django 4.1.3 on 2023-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_installedservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedservice',
            name='service_install_command',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='installedservice',
            name='service_uninstall_command',
            field=models.JSONField(null=True),
        ),
    ]
