# Generated by Django 4.1.3 on 2023-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_alter_installedservice_service_install_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedservice',
            name='install_log',
            field=models.TextField(null=True),
        ),
    ]
