# Generated by Django 4.1.3 on 2023-02-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_installedservice_install_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(null=True)),
                ('service_version', models.TextField(null=True)),
                ('service_type', models.TextField(default='database', null=True)),
                ('service_os', models.TextField(default='centos', null=True)),
                ('service_port', models.IntegerField(null=True)),
                ('service_install_command', models.JSONField(null=True)),
                ('service_uninstall_command', models.JSONField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='installedservice',
            name='service_install_command',
        ),
        migrations.RemoveField(
            model_name='installedservice',
            name='service_uninstall_command',
        ),
        migrations.AlterField(
            model_name='installedservice',
            name='ec2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_service', to='aws.ec2'),
        ),
        migrations.AddField(
            model_name='installedservice',
            name='installable_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installed_service', to='aws.installableservice'),
            preserve_default=False,
        ),
    ]
