# Generated by Django 4.1.3 on 2023-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_installableservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedservice',
            name='service_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed')], default=1, null=True),
        ),
    ]
