# Generated by Django 4.1.3 on 2023-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_alter_installedservice_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='ec2_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed'), (-2, 'Terminated')], default=1),
        ),
        migrations.AlterField(
            model_name='installedservice',
            name='service_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed'), (-2, 'Terminated')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lb',
            name='lb_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed'), (-2, 'Terminated')], default=1),
        ),
    ]
