# Generated by Django 3.2.17 on 2023-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscreds',
            name='aws_access_key_en',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='awscreds',
            name='aws_access_secret_en',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='awscreds',
            name='aws_private_key_pair_pem_en',
            field=models.BinaryField(null=True),
        ),
    ]
