# Generated by Django 3.2.17 on 2023-02-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscreds',
            name='aws_access_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='awscreds',
            name='aws_access_secret',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='awscreds',
            name='aws_private_key_pair_pem',
            field=models.BinaryField(null=True),
        ),
    ]
