# Generated by Django 3.2.17 on 2023-02-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_auto_20230225_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awscreds',
            old_name='aws_access_key',
            new_name='aws_access_key_en',
        ),
        migrations.RenameField(
            model_name='awscreds',
            old_name='aws_access_secret',
            new_name='aws_access_secret_en',
        ),
        migrations.RenameField(
            model_name='awscreds',
            old_name='aws_private_key_pair_pem',
            new_name='aws_private_key_pair_pem_en',
        ),
    ]
