# Generated by Django 3.2.17 on 2023-04-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_auto_20230225_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2MetaBasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=100)),
                ('VCpu', models.IntegerField(null=True)),
                ('Memory_in_mb', models.IntegerField(null=True)),
                ('region_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ec2',
            name='ec2_status',
            field=models.IntegerField(choices=[(-1, 'Prepared'), (1, 'Pending'), (2, 'Starting'), (3, 'Running'), (4, 'Stopping'), (5, 'Stopped'), (6, 'Shutting Down'), (7, 'Terminated')], default=-1),
        ),
        migrations.AlterField(
            model_name='installedservice',
            name='service_status',
            field=models.IntegerField(choices=[(-1, 'Prepared'), (1, 'Pending'), (2, 'Starting'), (3, 'Running'), (4, 'Stopping'), (5, 'Stopped'), (6, 'Shutting Down'), (7, 'Terminated')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='lb',
            name='lb_status',
            field=models.IntegerField(choices=[(-1, 'Prepared'), (1, 'Pending'), (2, 'Starting'), (3, 'Running'), (4, 'Stopping'), (5, 'Stopped'), (6, 'Shutting Down'), (7, 'Terminated')], default=-1),
        ),
    ]
