# Generated by Django 3.2.17 on 2023-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_auto_20230407_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='image_id',
            field=models.TextField(default='ami-006dcf34c09e50022'),
        ),
    ]
