# Generated by Django 3.2.17 on 2023-04-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_alter_ec2_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(max_length=21)),
                ('cidr', models.CharField(max_length=21)),
                ('region', models.CharField(max_length=21)),
                ('state', models.CharField(max_length=21)),
                ('options', models.CharField(max_length=21)),
                ('dhcp_options_id', models.CharField(max_length=21)),
                ('routes_table_id', models.CharField(max_length=21)),
                ('internet_gateway_id', models.CharField(max_length=21)),
                ('owner_id', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_id', models.CharField(max_length=24)),
                ('arn', models.CharField(max_length=66)),
                ('route_table_id', models.CharField(max_length=21)),
                ('cidr', models.CharField(max_length=21)),
                ('region', models.CharField(max_length=21)),
                ('state', models.CharField(max_length=21)),
                ('availability_zone', models.CharField(max_length=21)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.vpc')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=100)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.vpc')),
            ],
        ),
    ]
