# Generated by Django 3.2.17 on 2023-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_securitygroup_subnet_vpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpc',
            name='options',
        ),
        migrations.AlterField(
            model_name='vpc',
            name='dhcp_options_id',
            field=models.CharField(max_length=30),
        ),
    ]
