# Generated by Django 3.2.17 on 2023-04-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_auto_20230408_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='region',
        ),
    ]
