# Generated by Django 3.2.17 on 2023-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_remove_subnet_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='arn',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='availability_zone',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='cidr',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='route_table_id',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='state',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='cidr',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='dhcp_options_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='internet_gateway_id',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='region',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='routes_table_id',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='state',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
