# Generated by Django 3.2.17 on 2023-04-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_auto_20230409_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='route_table_id',
            new_name='route_table_ids',
        ),
    ]
