# Generated by Django 3.2.17 on 2023-04-09 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0012_rename_route_table_id_subnet_route_table_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='route_table_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=21), null=True, size=None),
        ),
    ]
