# Generated by Django 3.2.17 on 2023-04-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0013_alter_subnet_route_table_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitygroup',
            name='vpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_group', to='aws.vpc'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='vpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnet', to='aws.vpc'),
        ),
    ]
