# Generated by Django 3.2.17 on 2023-06-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0015_alter_vpc_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDS',
            fields=[
                ('awscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aws.awscomponent')),
                ('aws_component', models.TextField(default='rds')),
                ('rds_resource_id', models.TextField(null=True)),
                ('rds_endpoint', models.TextField(null=True)),
                ('rds_port', models.IntegerField(null=True)),
                ('rds_status', models.IntegerField(choices=[(-1, 'Prepared'), (1, 'Pending'), (2, 'Starting'), (3, 'Running'), (4, 'Stopping'), (5, 'Stopped'), (6, 'Shutting Down'), (7, 'Terminated')], default=-1)),
                ('rds_engine', models.TextField(default='PostgreSQL')),
                ('rds_engine_version', models.TextField(default='14.7')),
                ('rds_instance_class', models.TextField(default='db.t2.micro')),
                ('rds_allocated_storage', models.IntegerField(default=5)),
                ('rds_db_name', models.TextField(default='rdsdatabase')),
                ('rds_master_username', models.TextField(default='postgres')),
                ('rds_master_user_password', models.TextField(default='postgres')),
                ('rds_security_group', models.TextField(null=True)),
                ('rds_subnet1', models.TextField(null=True)),
                ('rds_subnet2', models.TextField(null=True)),
                ('rds_arn', models.TextField(null=True)),
            ],
            bases=('aws.awscomponent',),
        ),
        migrations.AddField(
            model_name='awscomponent',
            name='arn',
            field=models.TextField(null=True),
        ),
    ]
