# Generated by Django 3.2.17 on 2023-06-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0016_auto_20230607_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rds',
            name='rds_security_group',
        ),
        migrations.RemoveField(
            model_name='rds',
            name='rds_subnet1',
        ),
        migrations.RemoveField(
            model_name='rds',
            name='rds_subnet2',
        ),
        migrations.AddField(
            model_name='rds',
            name='rds_availability_zone',
            field=models.TextField(default='us-east-1b'),
        ),
        migrations.AddField(
            model_name='rds',
            name='rds_db_id',
            field=models.TextField(null=True),
        ),
    ]
