# Generated by Django 3.2.17 on 2023-06-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0019_rename_rds_db_id_rds_rds_db_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscomponent',
            name='subnet2',
            field=models.TextField(null=True),
        ),
    ]
