# Generated by Django 3.2.17 on 2023-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0020_awscomponent_subnet2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rds',
            name='rds_engine',
            field=models.TextField(default='postgres'),
        ),
    ]
