# Generated by Django 4.1.3 on 2022-12-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_awscreds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='ec2_instance_id',
            field=models.TextField(null=True),
        ),
    ]
