# Generated by Django 4.1.3 on 2022-12-31 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plan_delete_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.plan')),
                ('deploy_status', models.TextField(choices=[('Prepared', 'Prepared'), ('Deployed', 'Deployed')])),
                ('running_status', models.TextField(choices=[('Started', 'Started'), ('Running', 'Running'), ('Stopped', 'Stopped'), ('Failed', 'Failed')])),
            ],
        ),
    ]
