# Generated by Django 4.1.3 on 2022-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plan_deploy_status_plan_running_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deploy_status',
            field=models.TextField(default='PREPARED', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='running_status',
            field=models.TextField(default='STARTED', null=True),
        ),
    ]
