# Generated by Django 4.1.3 on 2022-12-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_plan_deploy_status_alter_plan_running_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deploy_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='running_status',
            field=models.TextField(null=True),
        ),
    ]
