# Generated by Django 4.1.3 on 2023-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_plan_deploy_status_alter_plan_running_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='deploy_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Deployed'), (0, 'Failed')], null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='running_status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Running'), (3, 'Stopped'), (0, 'Failed')], null=True),
        ),
    ]
