# Generated by Django 4.1.3 on 2023-01-17 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_plan_deploy_status_alter_plan_running_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2',
            name='date_created_or_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ec2',
            name='ec2_status',
            field=models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed')], default=1),
        ),
        migrations.AddField(
            model_name='ec2',
            name='image_id',
            field=models.TextField(default='ami-0f5e8a042c8bfcd5e'),
        ),
        migrations.AddField(
            model_name='ec2',
            name='instance_type',
            field=models.TextField(default='t2.micro'),
        ),
        migrations.AddField(
            model_name='ec2',
            name='region',
            field=models.TextField(default='us-west-1'),
        ),
        migrations.AddField(
            model_name='ec2',
            name='securityGroup',
            field=models.TextField(default='NOT-SET'),
        ),
        migrations.AddField(
            model_name='ec2',
            name='subnet',
            field=models.TextField(default='NOT-SET'),
        ),
    ]
