# Generated by Django 4.1.3 on 2023-01-20 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_ec2_owner_ec2_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(default='us-west-1')),
                ('securityGroup', models.TextField(default='NOT-SET')),
                ('subnet', models.TextField(default='NOT-SET')),
                ('date_created_or_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aws_components', to='api.plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='date_created_or_modified',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='region',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='securityGroup',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='subnet',
        ),
        migrations.CreateModel(
            name='LB',
            fields=[
                ('awscomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.awscomponent')),
                ('lb_instance_id', models.TextField(null=True)),
                ('lb_status', models.IntegerField(choices=[(1, 'Prepared'), (2, 'Started'), (3, 'Stopped'), (4, 'Deleted'), (10, 'Running'), (-1, 'Failed')], default=1)),
                ('lb_type', models.TextField(default='ALB')),
            ],
            bases=('api.awscomponent',),
        ),
        migrations.AddField(
            model_name='ec2',
            name='awscomponent_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.awscomponent'),
            preserve_default=False,
        ),
    ]
