# Generated by Django 4.1.3 on 2023-01-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_awscomponent_remove_ec2_date_created_or_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2',
            name='aws_component',
            field=models.TextField(default='ec2'),
        ),
        migrations.AddField(
            model_name='lb',
            name='aws_component',
            field=models.TextField(default='lb'),
        ),
    ]
