# Generated by Django 4.1.3 on 2023-01-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_plan_options_remove_awscomponent_securitygroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awscreds',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ec2',
            name='awscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='lb',
            name='awscomponent_ptr',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='AWSComponent',
        ),
        migrations.DeleteModel(
            name='AwsCreds',
        ),
        migrations.DeleteModel(
            name='EC2',
        ),
        migrations.DeleteModel(
            name='LB',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
