name: Django CI

on:
  push:
    branches: [ git-action-eslint ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.16]

    steps:
    - uses: actions/checkout@v3
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo yum -y install python-pip
        python3 -m pip install --upgrade pip
        pip install -r config/requirements/production.txt
      working-directory: api/django_api
    - name: Migrate App
      run: |
        python3 manage.py makemigrations > /tmp/migration.txt
      working-directory: api/django_api

