name: Django CI

on:
  push:
    branches: [back_to_life2]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.16]

    steps:
      - uses: actions/checkout@v3
      #     - name: Set up Python ${{ matrix.python-version }}
      #       uses: actions/setup-python@v3
      #       with:
      #         python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo yum -y install python-pip
          python3 -m pip install --upgrade pip
          pip install -r config/requirements/base.txt
          pip install -r config/requirements/production.txt
        working-directory: api/django_api
      - name: Migrate App
        run: |
          python3 manage.py makemigrations > /tmp/migration.txt
          python3 manage.py migrate
          sudo mkdir -p /var/www/build
          mkdir -p /home/ec2-user/encrypt_keys
          mkdir -p /home/ec2-user/logs
        working-directory: api/django_api
      - name: Prep env
        run: |
          echo 'AWS_TEST_MODE=False' > /home/ec2-user/django-deploy/django-work/cloudskin/cloudskin/api/django_api/.env
          echo 'CS_DATABASE_URL=postgres://cs:cs@localhost:5432/cs_db' >> /home/ec2-user/django-deploy/django-work/cloudskin/cloudskin/api/django_api/.env
          echo 'CS_JWT_SIGNING_KEY=None' >> /home/ec2-user/django-deploy/django-work/cloudskin/cloudskin/api/django_api/.env
          echo 'CS_SECRET_KEY="django-insecure-^i93n1dzwm_$fkupi+ck#!ngk^=))ih#$+a4f$46^15m&#c*ks"' >> /home/ec2-user/django-deploy/django-work/cloudskin/cloudskin/api/django_api/.env
      - name: Run backend service
        run: |
          nohup gunicorn wsgi:application --bind 0.0.0.0:8000 &
        working-directory: api/django_api
