# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Frontend CI/CD

on:
  push:
    branches: [ git-action-eslint ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json
    - run: npm i
      working-directory: front-end
    - run: npm test
      working-directory: front-end    
    - run: npm run build
      working-directory: front-end    
    - run: sudo rm -rf /usr/share/nginx/html/build/
      working-directory: front-end    
    - run: sudo mv /home/ec2-user/test-react/_work/hello-react/hello-react/front-end/build /usr/share/nginx/html
    # - run: sudo systemctl restart nginx
